# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    upload_to_play_store(
      version_code: options[:version_code],
      aab: "./app/release/app-release.aab"
    )
  end

  desc "Frame screenshots and copy to android metadata folder"
  lane :frame do |options|
    frameit(path: "./fastlane/screenshots")
  end
end
